### ISSUE TITLE
The package is not working for me.

### ISSUE THREAD

**Issue by paveltretyakovru** [vvo/offline-docs#2]
My steps:
```
~ $ npm install -g offline-docs
~ $ git clone https://github.com/airbnb/enzyme.git
~ $ cd enzyme
enzyme $ offline-docs
```
Then I have opened http://0.0.0.0:5000/ and that's all - I have ERR_ADDRESS_INVALID error.
I have tryied that on the Linux and Windows machines. :)

Maybe the package don't finished and I don't know about it?

The best regards, Pavel Tretyakov.

**Comment by vvo** [comment]
Just tried it, it takes A LOT of time because enzyme has A LOT of dependencies. It's also broken because now npm flatten dependencies and you end up not only with direct dependencies but basically ALL dependencies.

![image](https://user-images.githubusercontent.com/123822/27224253-6522faee-5294-11e7-8884-f0492781e9e6.png)

This tool is cool but very old, could be enhanced by reading package.json and only displaying documentations from those direct dependencies.

Good luck.

**Comment by paveltretyakovru** [comment]
Ok, thanks, @vvo. I am going to deal with it.

Regards, Pavel.
